### ISSUE TITLE
led strips not available

### ISSUE THREAD

**Issue by dondiego9999** [ilcato/homebridge-fibaro-hc3#1]
It is not possible to change the state of LED strips. They do not who in the home app

**Comment by ilcato** [comment]
@dondiego9999, can you detail describe your case?

**Comment by vvsokolov** [comment]
> @dondiego9999, can you detail describe your case?

I  have the same issue: Fibaro RGBW Controller2 not shown in Accessories.

**Comment by vvsokolov** [comment]
@ilcato, can I help you to localize error ?

**Comment by ilcato** [comment]
Can you check the type attribute in the device api?  I do not have such a devices. I'm looking for com.fibaro.FGRGBW441M and com.fibaro.colorController.

**Comment by KostuaD** [comment]
New controller has type - com.fibaro.FGRGBW442

**Comment by KostuaD** [comment]
<img width="1223" alt="Screenshot 2020-06-25 at 23 48 31" src="https://user-images.githubusercontent.com/67440815/85794025-9bebd200-b73e-11ea-8350-411fbe00224b.png">
<img width="1214" alt="Screenshot 2020-06-25 at 23 48 50" src="https://user-images.githubusercontent.com/67440815/85794038-a1e1b300-b73e-11ea-8647-cee4cd2205b9.png">

**Comment by ilcato** [comment]
@KostuaD, just published version 1.0.4. Can you try it?

**Comment by KostuaD** [comment]
> @KostuaD, just published version 1.0.4. Can you try it?

Hello!
Updated to version 1.0.4. The module is registered.
I can turn it on and off, but there is no way to adjust the brightness, and accordingly I can not change the color of the glow of the LED strip.
Thanks you!

**Comment by ilcato** [comment]
@KostuaD, can you send me the whole json object associated to the new device types?

**Comment by KostuaD** [comment]
Please tell me which file is needed and where to find it

**Comment by KostuaD** [comment]
[template-155-com.fibaro.FGRGBW442CC.zip](https://github.com/ilcato/homebridge-fibaro-hc3/files/4840989/template-155-com.fibaro.FGRGBW442CC.zip)
This is a template loaded with Fibaro HC3

**Comment by ilcato** [comment]
@KostuaD, select the icon with the symbol {...} in the lower left of the Fibaro Home Center web site.
Select "Devices" ine the "Select a definition" combo box.
Select "GET ​/devices​/{deviceID}" row in the list.
Click on "Try it out"
Insert deviceId and press execute.
Post here the resulted response.

Thanks

**Comment by vvsokolov** [comment]
{
  "id": 148,
  "name": "Лента (09)",
  "roomID": 220,
  "view": [
    {
      "assetsPath": "/dynamic-plugins/com.fibaro.rgbwController/assets",
      "jsPath": "/dynamic-plugins/com.fibaro.rgbwController",
      "name": "com.fibaro.rgbwController",
      "translatesPath": "/dynamic-plugins/com.fibaro.rgbwController/i18n",
      "type": "ts"
    }
  ],
  "type": "com.fibaro.FGRGBW442CC",
  "baseType": "com.fibaro.colorController",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 145,
  "viewXml": false,
  "configXml": false,
  "interfaces": [
    "levelChange",
    "light",
    "zwave",
    "zwaveAlarm",
    "zwaveMultiChannelAssociation",
    "zwaveProtection"
  ],
  "properties": {
    "parameters": [],
    "pollingTimeSec": 0,
    "zwaveCompany": "Fibargroup",
    "zwaveInfo": "3,6,4",
    "zwaveVersion": "5.0",
    "RFProtectionState": 0,
    "RFProtectionSupport": 0,
    "alarmLevel": 0,
    "alarmType": 0,
    "categories": [
      "lights"
    ],
    "color": "255,0,0,0",
    "configured": true,
    "currentProgram": 0,
    "currentProgramID": 0,
    "dead": false,
    "deadReason": "",
    "deviceControlType": 50,
    "deviceIcon": 15,
    "emailNotificationID": 0,
    "emailNotificationType": 0,
    "endPointId": 1,
    "isLight": true,
    "localProtectionState": 0,
    "localProtectionSupport": 0,
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": true,
    "model": "",
    "nodeId": 29,
    "parametersTemplate": "849",
    "productInfo": "1,15,9,2,16,0,5,0",
    "programsSortOrder": "1,2,3,4,5",
    "protectionExclusiveControl": 0,
    "protectionExclusiveControlSupport": false,
    "protectionState": 0,
    "protectionTimeout": 0,
    "protectionTimeoutSupport": false,
    "pushNotificationID": 0,
    "pushNotificationType": 0,
    "saveLogs": true,
    "serialNumber": "h'0000000000001e70",
    "smsNotificationID": 0,
    "smsNotificationType": 0,
    "state": false,
    "useTemplate": true,
    "userDescription": "",
    "value": 0
  },
  "actions": {
    "reconfigure": 0,
    "setColor": 1,
    "setValue": 1,
    "startLevelDecrease": 0,
    "startLevelIncrease": 0,
    "startProgram": 1,
    "stopLevelChange": 0,
    "toggle": 0,
    "turnOff": 0,
    "turnOn": 0
  },
  "created": 1592927178,
  "modified": 1592927178,
  "sortOrder": 22
}

**Comment by ilcato** [comment]
@vvsokolov, they changed the api for setting the color. Are you able to test the interface of the setColor action? Without a working device I'm not able to check it. Thanks.

**Comment by vvsokolov** [comment]
> @vvsokolov, they changed the api for setting the color. Are you able to test the interface of the setColor action? Without a working device I'm not able to check it. Thanks.

yes, I can

**Comment by vvsokolov** [comment]
@ilcato is it version for testing ?

**Comment by vvsokolov** [comment]
@ilcato , Fibaro release firmware 5.040.37

**Comment by ilcato** [comment]
@vvsokolov can you check how the setColor action works by calling the API directly?

**Comment by dior4ik** [comment]
Hi! The same issue. RGBW can be only switched on or off, but brightness control does not work. I can help you to debug the issue if you tell me what you want.

**Comment by ilcato** [comment]
@dior4ik I nee you to try to call the setColor action API in order to understand what I need to pass to it.

**Comment by dior4ik** [comment]
I don't have an RGB strip and use Fibaro RGBW only to switch it On, Off and control brightness. Now only On and Off features are working. Here is a sample request for controlling brightness:

curl -X POST "http://192.168.13.224/api/devices/141/action/setValue" -H  "accept: */*" -H  "Content-Type: application/json" -H  "X-Fibaro-Version: 2" -H  "Accept-language: en" -H  "Authorization: Basic .........." -d "{\"args\":[100]}"

<img width="874" alt="image" src="https://user-images.githubusercontent.com/2227237/101549867-1344b380-39b7-11eb-88f6-e4aca556038b.png">

**Comment by ilcato** [comment]
@dondiego9999 , @vvsokolov , @dior4ik , @KostuaD can you test latest version of the plugin for this issue ?

**Comment by KostuaD** [comment]
Hello ilcato! 
In new version of plugin test passed. 
Fibaro RGBW Controller2 work correctly. Brightness, color, switch on and off all worked.
Thank you!
