### ISSUE TITLE
question about uniqueSeed

### ISSUE THREAD

**Issue by 10der** [ilcato/homebridge-fibaro-hc3#14]
@ilcato why?
let uniqueSeed = shadowAccessory.name + shadowAccessory.roomID;
why not
let uniqueSeed = shadowAccessory.deviceID; ??!!

what the motivation to use the surrogate key?

**Comment by ilcato** [comment]
@10der because if two different device in different rooms have the same name there will be a uuid clash.

**Comment by odenisenko** [comment]
Sir. I am askinh about DeviceID what uniq for HCx
always!

**Comment by odenisenko** [comment]
why we can't use device.id instead of surrogate key

**Comment by odenisenko** [comment]
ahh. maybe i know.
cuz sometimes the device can be removed and added... with a new ID.

ok. closed
