### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by theuksbest** [ilcato/homebridge-fibaro-hc3#15]
Thanks for all the efforts that have gone into this integration!

Looking for some help and ideas, having a problem connecting the HOOBS plugin with HC3 - getting an error like cannot read property “name” of null.
 
I have it setup as recommended i think, and dont see anything obvious. 

{
  "name": "FibaroHC3",
  "host": "192.168.x.x",
  "username": "admin",
  "password": "****"
}

Any thoughts what i could try next?
 
Full error below from logs
 
[HC3-00002499] Error getting data from Home Center: TypeError: Cannot read property 'name' of null at Function.createShadowAccessory (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/shadows.js:102:68) at /home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:148:61 at Array.map (<anonymous>) at FibaroHC3.LoadAccessories (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:145:17) at FibaroHC3.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:106:22) at Generator.next (<anonymous>) at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:38:58) at processTicksAndRejections (internal/process/task_queues.js:97:5)01/12/2020, 16:25:40 (node:637) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null01/12/2020, 16:25:40 at Function.createShadowAccessory (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/shadows.js:102:68)01/12/2020, 16:25:40 at /home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:148:6101/12/2020, 16:25:40 at Array.map (<anonymous>)01/12/2020, 16:25:40 at FibaroHC3.LoadAccessories (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:145:17)01/12/2020, 16:25:40 at FibaroHC3.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:106:22)01/12/2020, 16:25:40 at Generator.next (<anonymous>)01/12/2020, 16:25:40 at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-fibaro-hc3/dist/index.js:38:58)01/12/2020, 16:25:40 at processTicksAndRejections (internal/process/task_queues.js:97:5)01/12/2020, 16:25:40 (node:637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)01/12/2020, 16:25:40 (node:637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vac-pav** [comment]
I have the same problem when using with homebridge. Only 1.0.6 is causing problems, 1.0.5 is running fine.

**Comment by theuksbest** [comment]
@vac-pav - good to know, I’m not sure in HOOBS how to select a previous version to install instead. Hopefully they fix then and release an update soon

**Comment by ilcato** [comment]
@theuksbest @vac-pav can you test version 1.0.7 ?

**Comment by vac-pav** [comment]
@ilcato 1.0.7 seems to work OK. Thanks for the error correction.

**Comment by ilcato** [comment]
Fixed

**Comment by theuksbest** [comment]
Agree, seems to be working now. @ilcato many thanks!
