### ISSUE TITLE
reset cache, looses assignments in homekit for some devices only

### ISSUE THREAD

**Issue by flipoidix** [ilcato/homebridge-fibaro-hc3#18]
Hi, 

I'm having a problem with some devices, if I need to clear the cache of the homebridge, I loose all assignments in homekit, but not for all devices.

Example:

"com.fibaro.rollerShutter" and "Outlet" are recognized as the same devices after reseting cache

"com.fibaro.binarySwitch" loose assignments, 

Is there anything you can do to prevent this? Is it possible to keep the fibaro ID's or something that identifies the device as being the same?

Thank you

**Comment by ilcato** [comment]
Normally after clearing the cache the device are reconstructed from scratch. If you use the homebridge UI you can selectively remove from cache a single device.
