### ISSUE TITLE
Support for Thermostats

### ISSUE THREAD

**Issue by vvsokolov** [ilcato/homebridge-fibaro-hc3#2]
Hi, @ilcato !
Could you please add Thermostats support ?
Now operatingMode is in the same device, but in it's "properties".
For example
"supportedThermostatModes": [
      "Off",
      "Heat"
    ],
"thermostatMode": "Heat"

**Comment by ilcato** [comment]
Waiting for a more stable HC3 firmware.

**Comment by vvsokolov** [comment]
I’m pretty sure that nothing will change in the API part. Or is there any reasonable doubt about this?

**Comment by ilcato** [comment]
Last week I was not able to test it.

**Comment by vvsokolov** [comment]
You can give me an untested version - I will try to test it.

**Comment by ilcato** [comment]
Tested manual call to the API with inconsistent results.

**Comment by vvsokolov** [comment]
The only problem is the thermostatMode ?

**Comment by ilcato** [comment]
No, stability and inconsistent results. The API seems clear,

**Comment by vvsokolov** [comment]
hm...Bad news :(

**Comment by vvsokolov** [comment]
But how Fibaro GUI works with inconsistent data from API ?

**Comment by ilcato** [comment]
Will check again the next firmware release.

**Comment by vvsokolov** [comment]
> Will check again the next firmware release.

5.031.33 is released!

Could you please check it ?

**Comment by vvsokolov** [comment]
> Will check again the next firmware release.

Any news ?

**Comment by ilcato** [comment]
It works well. As soon as I have a little free time I will implement it.

**Comment by vvsokolov** [comment]
> It works well. As soon as I have a little free time I will implement it.

let the force and little free time be with you

**Comment by ilcato** [comment]
A strange thing that is happening with the new firmware is that the device discovery doesn't report the actions list. I'm not sure if with the previous one it was available but I have problem with an home assistant instance that is no more working.

**Comment by vvsokolov** [comment]
> A strange thing that is happening with the new firmware is that the device discovery doesn't report the actions list. I'm not sure if with the previous one it was available but I have problem with an home assistant instance that is no more working.

Hm. Very strange. In the block-scene editor, this is available:
<img width="298" alt="Знімок екрана 2020-06-05 о 21 16 32" src="https://user-images.githubusercontent.com/4036031/83909791-1940aa00-a772-11ea-9bc5-d41d45d7bac0.png">

**Comment by vvsokolov** [comment]
Hello, @ilcato !
Any news ?

**Comment by vvsokolov** [comment]
Hello, @ilcato  !
Any news ?

**Comment by vvsokolov** [comment]
Hello, @ilcato  !
Any news ?

**Comment by flipoidix** [comment]
@ilcato 
Hi! any chance you could implement this thermostat functionality? thank you!

**Comment by ilcato** [comment]
@vvsokolov @flipoidix can you test version 1.1.9 ?

**Comment by advantio-techsec-team** [comment]
Hello! I think there is some bug in the new thermostat feature. When I try to change its status in HomeKit or Hoobs web UI, HC3 (5.070.42 firmware) becomes unresponsive. I can login to the admin panel, but can not control any device until I reboot it. And CPU load becomes high.
<img width="1323" alt="2021-03-27 22-22-14" src="https://user-images.githubusercontent.com/59699729/112734632-a1857b00-8f4f-11eb-8bbf-479dc03e3d59.png">

**Comment by ilcato** [comment]
@advantio-techsec-team which thermostat do you have?

**Comment by dior4ik** [comment]
@ilcato hi! The previous comment was mine, but I wrote it from the wrong account. I'm using Fibaro Heat Controller

**Comment by ilcato** [comment]
@dior4ik Fibaro Heat Controller is working for me, without problem. Try to remove it from cached accessories.

**Comment by flipoidix** [comment]
> @vvsokolov @flipoidix can you test version 1.1.9 ?

Hi, I'm using HC3 5.050.13 and v 1.1.10 but no thermostats appear on hb. ( I'm using linked devices as thermostats as well as quick apps ( of type thermostat auto ). does this only support real devices?

**Comment by ilcato** [comment]
No @flipoidix only real devices are supported.

**Comment by flipoidix** [comment]
> No @flipoidix only real devices are supported.

Any chance of using the virtual or linked ones? the quick app switches work perfectly for example is it possible to make it work with the quick app thermostats as well?

**Comment by ilcato** [comment]
Create an issue for an enhancement.

**Comment by flipoidix** [comment]
> Create an issue for an enhancement.

ok thanks
