### ISSUE TITLE
no support of "com.fibaro.hvacSystem" devices

### ISSUE THREAD

**Issue by vkamenski** [ilcato/homebridge-fibaro-hc3#21]
Hi,

Devices with the type "com.fibaro.hvacSystem" (specifically [heatit](https://manuals.heatit.com/PDF/Heatit%20Z-TRM3/Manual_Heatit_Z-TRM3_FW%204.0%20Ver2020-C_ENG.pdf) thermostat) don't appear in accessories list

**Comment by ilcato** [comment]
@vkamenski can you test version 1.1.9 ?

**Comment by vkamenski** [comment]
@ilcato v1.1.10 I can't find my heatit device in the list of accessories

**Comment by ilcato** [comment]
@vkamenski is the device type exactly "com.fibaro.hvacSystem" ? or "com.fibaro.hvacsystem"

**Comment by ilcato** [comment]
@vkamenski can you test homebridge-fibaro-hc3@1.1.11-beta.3

**Comment by ilcato** [comment]
1.1.1 published can you test your "com.fibaro.hvacSystem"

**Comment by vkamenski** [comment]
> @vkamenski is the device type exactly "com.fibaro.hvacSystem" ? or "com.fibaro.hvacsystem"

com.fibaro.hvacSystem

**Comment by vkamenski** [comment]
> 1.1.1 published can you test your "com.fibaro.hvacSystem"

it works! thank you
