### ISSUE TITLE
[Fibaro_HC3] Error getting data from Home Center:  Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by hoffmanncedric** [ilcato/homebridge-fibaro-hc3#25]
[2/21/2021, 12:20:44 PM] [Fibaro_HC3] Error getting data from Home Center:  Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
(node:3902) UnhandledPromiseRejectionWarning: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ilcato** [comment]
How did you configured the host parameter in config.json?

**Comment by hoffmanncedric** [comment]
![HC3](https://user-images.githubusercontent.com/26899103/108623830-602a1900-7441-11eb-8045-eb0f6abcc556.jpg)

**Comment by ilcato** [comment]
Is your Home Center exposing https interface?

**Comment by hoffmanncedric** [comment]
![HC3](https://user-images.githubusercontent.com/26899103/108623917-ed6d6d80-7441-11eb-9c5d-f78913d082cf.jpg)

**Comment by ilcato** [comment]
Please enable also the http interface.
I'm currently implementing the support also for https. I will keep you updated.

**Comment by hoffmanncedric** [comment]
I try but its locked, i will check this point on my side and reverse back to you when http will be activated, thanks for your quick support! :-)

**Comment by hoffmanncedric** [comment]
it's works!! thanks a lot!very good job!

**Comment by ilcato** [comment]
Check within a few hours, I should publish a release with https support.

**Comment by ilcato** [comment]
@hoffmanncedric, try new version. You should put in the new param "url" the address of your Home Center like:
`"url": "https://hc3-00000XXX.local"`
Then you need to obtain the ca.cer file from your Home Center and put it in the same folder as config.json.

**Comment by hoffmanncedric** [comment]
2/21/2021, 5:51:37 PM] [Fibaro_HC3] Error getting data from Home Center:  Error: getaddrinfo ENOTFOUND hc3-00014803.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hc3-00014803.local',
  response: undefined
}
(node:10159) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND hc3-00014803.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10159) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by ilcato** [comment]
@hoffmanncedric, where did you put the ca.cer file?

**Comment by hoffmanncedric** [comment]
![image](https://user-images.githubusercontent.com/26899103/108633135-eca0ff80-7472-11eb-8176-f2cd6d89dcc4.png)

**Comment by hoffmanncedric** [comment]
i try to copy the .cer into module and fibaro but same problem

![image](https://user-images.githubusercontent.com/26899103/108633278-b0ba6a00-7473-11eb-95e8-04e4f5e65e55.png)

**Comment by ilcato** [comment]
Are you running homebridge in docker?

**Comment by ilcato** [comment]
I'm currently looking in .homebridge in the user home directory or in the /var/lib/homebridge when you run the homebridge UX. Which setup are you running?

**Comment by hoffmanncedric** [comment]
yes my homebridge is on a docker on my synology nas, with last setup on homebridge for docker

**Comment by ilcato** [comment]
Are you able to tell the path as seen by the homebridge process?

**Comment by hoffmanncedric** [comment]
yes its here :
![image](https://user-images.githubusercontent.com/26899103/108633718-0a239880-7476-11eb-832a-861e267bd2eb.png)

**Comment by ilcato** [comment]
Are you using this: https://github.com/oznu/docker-homebridge ?

**Comment by ilcato** [comment]
@hoffmanncedric, can you try with 1.1.2 ? Leave ca.cer where you put it.

**Comment by hoffmanncedric** [comment]
![image](https://user-images.githubusercontent.com/26899103/108635719-2f69d400-7481-11eb-9cec-5231190d5e66.png)

**Comment by vkamenski** [comment]
@ilcato where should i put certificate for raspberry pi installation?

**Comment by hoffmanncedric** [comment]
update on 1.1.2
![image](https://user-images.githubusercontent.com/26899103/108638195-4662f300-748e-11eb-90b0-67b371d0b953.png)
i thinks its a warning

**Comment by hoffmanncedric** [comment]
![image](https://user-images.githubusercontent.com/26899103/108638388-4f07f900-748f-11eb-8e14-179617141fd6.png)
i will pass on http :-)

**Comment by galuszka** [comment]
If you use https (with cer file uploaded to homebridge) it will not accept access using an IP address because only hc-0000xxxx.local is listed in certificate subject alternative name. But when homebridge is running in docker container (on raspberry pi) the .local addresses are not resolved. Non-secure (http) access is not working either. It is always complaining about the certificate like mentioned by @hoffmanncedric above.

**Comment by ilcato** [comment]
For http use host param and delete url param.

**Comment by vkamenski** [comment]
I'm using raspberry image, https, and url param. My ca.cer file is in "/var/lib/homebridge/" folder. I'm still getting

```
[22/02/2021, 23:21:42] [FibaroHC3] Error getting data from Home Center:  Error: getaddrinfo ENOTFOUND hc3-00014186.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hc3-00014186.local',
  response: undefined
}
```

**Comment by ilcato** [comment]
> If you use https (with cer file uploaded to homebridge) it will not accept access using an IP address because only hc-0000xxxx.local is listed in certificate subject alternative name. But when homebridge is running in docker container (on raspberry pi) the .local addresses are not resolved. Non-secure (http) access is not working either. It is always complaining about the certificate like mentioned by @hoffmanncedric above. In the end I cannot make the 1.1.2 plugin working :-(

@galuszka, I confirm that no docker support is present for this feature. But you can use http by using the host param and removing the url param as it was before this change.

**Comment by ilcato** [comment]
> I'm using raspberry image, https, and url param. My ca.cer file is in "/var/lib/homebridge/" folder. I'm still getting
> 
> ```
> [22/02/2021, 23:21:42] [FibaroHC3] Error getting data from Home Center:  Error: getaddrinfo ENOTFOUND hc3-XXX.local
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
>   errno: -3008,
>   code: 'ENOTFOUND',
>   syscall: 'getaddrinfo',
>   hostname: 'hc3-XXX.local',
>   response: undefined
> }
> ```

@vkamenski, are you able to resolve HC3 name from the raspberry?

**Comment by ilcato** [comment]
> ![image](https://user-images.githubusercontent.com/26899103/108638388-4f07f900-748f-11eb-8e14-179617141fd6.png)
> i will pass on http :-)

@hoffmanncedric, as @galuszka said this doesn't work on Docker. Sorry.
