### ISSUE TITLE
Wrong status representation for dimmers

### ISSUE THREAD

**Issue by danholt-international** [ilcato/homebridge-fibaro-hc3#31]
All dimmers that are set ON, but dimmed in a range from 1%-99% are shown as OFF. Only when dimmers are set to 100% intensity, device tiles shown ON status.
As this error already is visible in the homebridge web UI devices section, this error persist in Home app too.
<img width="248" alt="Bildschirmfoto 2021-03-05 um 18 39 18" src="https://user-images.githubusercontent.com/52234886/110152736-607fc800-7de2-11eb-8aa2-7672dbd7d38c.png">

**Comment by ilcato** [comment]
@danholt-international try version 1.1.6

**Comment by danholt-international** [comment]
Hi!

Dimmers are working again.

Unfortunately still missing:
Support for Heat Controller valves
Support of RGBW Controller 2

Cheers
