### ISSUE TITLE
Support for RGBW Controller 2

### ISSUE THREAD

**Issue by danholt-international** [ilcato/homebridge-fibaro-hc3#32]
Please add or fix support for Fibaro RGBW Controller 2

Currently only ON / OFF works. Choosing Color won`t work and generates an error in HomeKit telling "no answer" from device.
As well dimming doesn't work and also ends up in the message "no answer" from device.

**Comment by ilcato** [comment]
Working on it

**Comment by ilcato** [comment]
@danholt-international can you test version 1.1.7 ?

**Comment by danholt-international** [comment]
Hello!

Great work! Version 1.1.7 brings back HeatController and RGBW Controller support is fine.
Dimming works, Color selection works fine now.

Thanks a lot!
I will spend some coffee soon!

Regards

Daniel

**Comment by danholt-international** [comment]
5 Coffees on the way…

Cheers!
Daniel

**Comment by danholt-international** [comment]
Hello!

I am confused about these two software versions: 

"Homebridge Fibaro Home Center" and „Homebridge Fibaro Hc3“

Looks like the „Homebridge Fibaro Hc3“ is outdated and you created a new version that includes support for all HC2 and HC3 incl. Yubii .

Is there a possibility to make a smooth update without killing all existing Homekit entries in Home App?

￼


Regards

Daniel
