### ISSUE TITLE
Carbon Monoxide NaN error

### ISSUE THREAD

**Issue by afendikov** [ilcato/homebridge-fibaro-hc3#33]
Hello,

I have Fibaro CO sensor and here is error in log in Homebridge ( using now 1.1.6, but error appears last 3 versions of plugin ):

[3/23/2021, 1:47:13 AM] [homebridge-fibaro-hc3] This plugin generated a warning from the characteristic 'Carbon Monoxide Peak Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

[3/23/2021, 1:47:13 AM] [homebridge-fibaro-hc3] Error: 
    at CarbonMonoxidePeakLevel.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CarbonMonoxidePeakLevel.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CarbonMonoxidePeakLevel.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at GetFunctions.returnValue (/usr/lib/node_modules/homebridge-fibaro-hc3/src/getFunctions.ts:85:19)
    at GetFunctions.getFloat (/usr/lib/node_modules/homebridge-fibaro-hc3/src/getFunctions.ts:106:8)
    at FibaroHC3.<anonymous> (/usr/lib/node_modules/homebridge-fibaro-hc3/src/index.ts:383:29)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-fibaro-hc3/dist/index.js:39:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

It still showing in Home app on iPhone

![IMG_2653](https://user-images.githubusercontent.com/51122271/112073109-0a4dab80-8b7c-11eb-9b21-76d39a4d77c7.PNG)

**Comment by ilcato** [comment]
@afendikov, can you update to last version and check if this is still an issue?

**Comment by afendikov** [comment]
@ilcato , yes, still error in 1.1.10

**Comment by ilcato** [comment]
@afendikov, can you call the Fibaro Api in order to have the property object of this device ? Unfortunately I do not have this kind of device.

**Comment by afendikov** [comment]
Hello,

Here it is:

{

   - id: 51,
   - name: "co bedroom sensor",
   - roomID: 225,
   - view: [ ],
   - type: "com.fibaro.FGCD001",
   - baseType: "com.fibaro.coDetector",
   - enabled: true,
   - visible: true,
   - isPlugin: false,
   - parentId: 50,
   - viewXml: false,
   - configXml: false,
   - interfaces:
   [
      - "battery",
      - "fibaroBreach",
      - "fibaroFirmwareUpdate",
      - "tamper",
      - "zwave",
      - "zwaveAlarm",
      - "zwaveMultiChannelAssociation",
      - "zwaveWakeup"
      ],
   - properties:
   {
      - parameters:
      [
         -
         {
            - id: 2,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 1,
            - value: 0
            },
         -
         {
            - id: 3,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 1,
            - value: 0
            },
         -
         {
            - id: 4,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 1,
            - value: 0
            },
         -
         {
            - id: 7,
            - lastReportedValue: 63,
            - lastSetValue: 63,
            - size: 1,
            - value: 63
            },
         -
         {
            - id: 10,
            - lastReportedValue: 3,
            - lastSetValue: 3,
            - size: 1,
            - value: 3
            },
         -
         {
            - id: 11,
            - lastReportedValue: 255,
            - lastSetValue: 255,
            - size: 2,
            - value: 255
            },
         -
         {
            - id: 12,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 2,
            - value: 0
            },
         -
         {
            - id: 13,
            - lastReportedValue: 3,
            - lastSetValue: 3,
            - size: 1,
            - value: 3
            },
         -
         {
            - id: 14,
            - lastReportedValue: 40,
            - lastSetValue: 40,
            - size: 2,
            - value: 40
            },
         -
         {
            - id: 15,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 2,
            - value: 0
            },
         -
         {
            - id: 16,
            - lastReportedValue: 255,
            - lastSetValue: 255,
            - size: 2,
            - value: 255
            },
         -
         {
            - id: 17,
            - lastReportedValue: 25,
            - lastSetValue: 25,
            - size: 2,
            - value: 25
            },
         -
         {
            - id: 19,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 2,
            - value: 0
            },
         -
         {
            - id: 20,
            - lastReportedValue: 0,
            - lastSetValue: 0,
            - size: 2,
            - value: 0
            },
         -
         {
            - id: 21,
            - lastReportedValue: 2,
            - lastSetValue: 2,
            - size: 1,
            - value: 2
            },
         -
         {
            - id: 22,
            - lastReportedValue: 55,
            - lastSetValue: 55,
            - size: 1,
            - value: 55
            },
         -
         {
            - id: 23,
            - lastReportedValue: 1,
            - lastSetValue: 1,
            - size: 1,
            - value: 1
            },
         -
         {
            - id: 25,
            - lastReportedValue: 2,
            - lastSetValue: 2,
            - size: 1,
            - value: 2
            },
         -
         {
            - id: 26,
            - lastReportedValue: 30,
            - lastSetValue: 30,
            - size: 2,
            - value: 30
            }
         ],
      - pollingTimeSec: 0,
      - wakeUpTime: 21600,
      - zwaveCompany: "Fibargroup",
      - zwaveInfo: "3,4,38",
      - zwaveVersion: "3.2",
      - alarmLevel: 0,
      - alarmType: 0,
      - batteryLevel: 100,
      - batteryLowNotification: true,
      - categories:
      [
         - "safety"
         ],
      - concentration: 0,
      - configured: true,
      - dead: false,
      - deadReason: "",
      - defInterval: 0,
      - deviceControlType: 0,
      - deviceIcon: 118,
      - emailNotificationID: 0,
      - emailNotificationType: 0,
      - endPointId: 0,
      - firmwareUpdate:
      {
         - info: "",
         - progress: 0,
         - status: "UpToDate",
         - updateVersion: "3.2"
         },
      - icon:
      {
         - path:
         "assets/icon/fibaro/com.fibaro.FGCD001/com.fibaro.FGCD001-healthy.png"
         ,
         - source: "HC"
         },
      - lastBreached: 0,
      - lastHealthy: 0,
      - lastModerate: 0,
      - log: "",
      - logTemp: "",
      - manufacturer: "",
      - markAsDead: true,
      - maxConcentration: 0,
      - maxInterval: 0,
      - minInterval: 0,
      - model: "",
      - nodeId: 7,
      - parametersTemplate: "783",
      - pendingActions: false,
      - productInfo: "1,15,18,1,16,0,3,2",
      - pushNotificationID: 0,
      - pushNotificationType: 0,
      - saveLogs: true,
      - serialNumber: "h'0000000000001018",
      - smsNotificationID: 0,
      - smsNotificationType: 0,
      - state: 0,
      - stepInterval: 0,
      - tamper: false,
      - unit: "",
      - updateVersion: "",
      - useTemplate: true,
      - userDescription: "",
      - value: false,
      - warningNotificationActive: true
      },
   - actions:
   {
      - abortUpdate: 1,
      - reconfigure: 0,
      - reset: 0,
      - retryUpdate: 1,
      - setInterval: 1,
      - startUpdate: 1,
      - updateFirmware: 1
      },
   - created: 1616928112,
   - modified: 1616928112,
   - sortOrder: 71

}

**Comment by ilcato** [comment]
@afendikov can you show me the panel in Home Center

**Comment by ilcato** [comment]
@afendikov can you test: homebridge-fibaro-hc3@0.1.120-beta.2

**Comment by afendikov** [comment]
@ilcato, beta works OK

Thank you!

[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Carbon Monoxide Detected
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Carbon Monoxide Level
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Carbon Monoxide Peak Level
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Battery Level
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Status Low Battery
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Battery Level
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  51  parameter: Charging State
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  52  parameter: Current Temperature
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  52  parameter: Status Low Battery
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  52  parameter: Battery Level
[3/28/2021, 10:57:06 PM] [FibaroHC3] Getting value from device:  52  parameter: Charging State

**Comment by ilcato** [comment]
Will publish it tomorrow.
