### ISSUE TITLE
fibaro heat controller

### ISSUE THREAD

**Issue by Sinoples** [ilcato/homebridge-fibaro-hc3#34]
Hi Ilcato, 

Can you uncomment the following code lines ? I am tested them with my FIBARO heat controller and it's OK, the APIs FIBARO are working.

https://github.com/ilcato/homebridge-fibaro-hc3/blob/f47fe7e5d3d07f57acb0b2a808a799cc03e53d39/src/shadows.ts#L236
To 
https://github.com/ilcato/homebridge-fibaro-hc3/blob/f47fe7e5d3d07f57acb0b2a808a799cc03e53d39/src/shadows.ts#L250

Thanks you a lot :)

**Comment by ilcato** [comment]
Will do in the next release. Stay tuned.

**Comment by ilcato** [comment]
@Sinoples can you test version 1.1.7 ?
