### ISSUE TITLE
Support for Global variables not only switch

### ISSUE THREAD

**Issue by KJTamas** [ilcato/homebridge-fibaro-hc3#36]
Hi @ilcato ,

It would be great, if Global variables not act only as a switch, but also as a dimmer. For example 1 byte, 0-255, 0 means false, greater then 0 true, if want to use as a switch, and 0 means off, and 1-255 means  as  a dimmer value. Of course this must be programmed in HC3.

thx

**Comment by ilcato** [comment]
@KJTamas Working on it

**Comment by ilcato** [comment]
@KJTamas, name your Global Variables acting as dimmers with a "dim-" prefix. I will remove it in HomeKit.

**Comment by ilcato** [comment]
@KJTamas can you test beta version:
`npm install homebridge-fibaro-hc3@beta`

**Comment by KJTamas** [comment]
Hi,

It’ working!

One thing. I don’t know, it’s a bug, or feature. If i open the accessories, and pull the slider e.g. 50%, in HC3 the variable values = 50. Then i close the accessories panel in HB, and turn off (one klick HC3 variable = 0), and then turn on, the HC3 variable get 100 not the prev 50. Original accessories panel remember the prev value.

Tamas

**Comment by ilcato** [comment]
Since I use the same variable for both the brightness and on/off status I cannot resume the previous brightness level.
Will publish this version.
