### ISSUE TITLE
https certificate

### ISSUE THREAD

**Issue by crlppr** [ilcato/homebridge-fibaro-hc3#6]
Hello, 

Thanks a lot, very good pluggings

In settings, network I have activated only https communication. When I do that I get this error. Do you know where / how can I install the certificate?.

Thanks in advance. 

[2020-9-15 19:29:53] [FibaroHC3] Error fetching updates:  Error: unable to get local issuer certificate
    at TLSWrap.verifyError (<anonymous>)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'

**Comment by ilcato** [comment]
@crlppr, you should execute
`export NODE_EXTRA_CA_CERTS="FIBARO CA CERTIFICATE FILE PATH"
`
before running home bridge.

You also need to specify the host by name and not by IP.

**Comment by Jame-Stitel** [comment]
Hi, I set the hostname to HC3-XXXXXXXX
executed
`export NODE_EXTRA_CA_CERTS="usr/share/ca-certificates/local/ca.cer"`
but still having this issue

**Comment by Jame-Stitel** [comment]
> Hello,
> 
> Thanks a lot, very good pluggings
> 
> In settings, network I have activated only https communication. When I do that I get this error. Do you know where / how can I install the certificate?.
> 
> Thanks in advance.
> 
> [2020-9-15 19:29:53] [FibaroHC3] Error fetching updates: Error: unable to get local issuer certificate
> at TLSWrap.verifyError ()
> at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
> at TLSSocket.emit (events.js:315:20)
> at TLSSocket._finishInit (_tls_wrap.js:936:8)
> at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
> code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'

Hi, did you manage to get this running? @crlppr

**Comment by Jame-Stitel** [comment]
Well, it actually does not throw that error regarding problem with certificate anymore, it does show fibaro accessories in Apple Home now, but I am not able to control them. It results in "no response". When I switch Fibaro to accept http, all is fine... so still issue with the ssl certificate?

**Comment by crlppr** [comment]
Hi Jame-Stitle, thanks a lot for your help. Finally, I managed using the following command. 

curl --cacert /home/pi/fibaro.cer -X PUT "https://HC3-00003xxx/api/scenes/117" -H "accept: */*" -H "Content-Type: application/json" -
H "X-Fibaro-Version: 2" -H "Accept-language: es" -H "Authorization: Basic YXXXXXXXXXXXXXXXXXXXXX=" -d "{\"id\":117,\"enabled\":false}"

**Comment by Jame-Stitel** [comment]
> Hi Jame-Stitle, thanks a lot for your help. Finally, I managed using the following command.
> 
> curl --cacert /home/pi/fibaro.cer -X PUT "https://HC3-00003xxx/api/scenes/117" -H "accept: _/_" -H "Content-Type: application/json" -
> H "X-Fibaro-Version: 2" -H "Accept-language: es" -H "Authorization: Basic YXXXXXXXXXXXXXXXXXXXXX=" -d "{"id":117,"enabled":false}"

Did you implement it with the homebridge code? Btw. are you using the hb-service?

**Comment by crlppr** [comment]
HI Jame-Stitel,

Sorry but No. This is just a .sh script executed from the Rapsberry PI to the Fibaro HC3. In the Raspberry PI, I'm able to manage the working and not working days and based on that, I'm activating or de-activating scenes in the HC3, for example, the wakeup scenes.
