### ISSUE TITLE
Fibaro Door or Window Sensor

### ISSUE THREAD

**Issue by Damianeq90** [ilcato/homebridge-fibaro-hc3#7]
Hi!

Does the plug support the Fibaro Door or Window Sensor? Unfortunately, I cannot see this device in my Homebridg ...?

**Comment by Sinoples** [comment]
Hi 
It s fixed, can u try.

**Comment by Damianeq90** [comment]
I understand that I should update your HomeBridge add-on? All the time he does not see the system of sensors opening doors and windows.

**Comment by Damianeq90** [comment]
ok I updated the shadows file but the door and window sensors are still not visible

**Comment by Sinoples** [comment]
I need Devise Type, can u execute REST API devise from your HC3 ? 
1. Take ID 
![image](https://user-images.githubusercontent.com/43269264/95266762-22cb4300-0834-11eb-9541-b09d3c064812.png)
2. Execute in the swagger REST API Devise
![image](https://user-images.githubusercontent.com/43269264/95266902-6e7dec80-0834-11eb-8b36-ddc2cb1d1d2b.png)
3. Reply with result

**Comment by Damianeq90** [comment]
Details
--
200 | Response bodyDownload{   "id": 133,   "name": "Okno",   "roomID": 220,   "view": [     {       "assetsPath": "/dynamic-plugins/com.fibaro.securitySensor/assets",       "jsPath": "/dynamic-plugins/com.fibaro.securitySensor",       "name": "com.fibaro.securitySensor",       "translatesPath": "/dynamic-plugins/com.fibaro.securitySensor/i18n",       "type": "ts"     }   ],   "type": "com.fibaro.FGDW002",   "baseType": "com.fibaro.doorWindowSensor",   "enabled": true,   "visible": true,   "isPlugin": false,   "parentId": 132,   "viewXml": false,   "configXml": false,   "interfaces": [     "battery",     "fibaroBreach",     "fibaroFirmwareUpdate",     "tamper",     "zwave",     "zwaveAlarm",     "zwaveMultiChannelAssociation",     "zwaveWakeup"   ],   "properties": {     "parameters": [       {         "id": 1,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 1,         "value": 0       },       {         "id": 2,         "lastReportedValue": 6,         "lastSetValue": 6,         "size": 1,         "value": 6       },       {         "id": 3,         "lastReportedValue": 3,         "lastSetValue": 3,         "size": 1,         "value": 3       },       {         "id": 11,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 1,         "value": 0       },       {         "id": 12,         "lastReportedValue": 255,         "lastSetValue": 255,         "size": 2,         "value": 255       },       {         "id": 13,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 2,         "value": 0       },       {         "id": 14,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 2,         "value": 0       },       {         "id": 15,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 2,         "value": 0       },       {         "id": 30,         "lastReportedValue": 5,         "lastSetValue": 5,         "size": 2,         "value": 5       },       {         "id": 31,         "lastReportedValue": 1,         "lastSetValue": 1,         "size": 1,         "value": 1       },       {         "id": 50,         "lastReportedValue": 300,         "lastSetValue": 300,         "size": 2,         "value": 300       },       {         "id": 51,         "lastReportedValue": 10,         "lastSetValue": 10,         "size": 2,         "value": 10       },       {         "id": 52,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 2,         "value": 0       },       {         "id": 53,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 2,         "value": 0       },       {         "id": 54,         "lastReportedValue": 0,         "lastSetValue": 0,         "size": 1,         "value": 0       },       {         "id": 55,         "lastReportedValue": 350,         "lastSetValue": 350,         "size": 2,         "value": 350       },       {         "id": 56,         "lastReportedValue": 100,         "lastSetValue": 100,         "size": 2,         "value": 100       }     ],     "pollingTimeSec": 0,     "wakeUpTime": 21600,     "zwaveCompany": "Fibargroup",     "zwaveInfo": "3,4,38",     "zwaveVersion": "3.2",     "alarmLevel": 0,     "alarmType": 0,     "batteryLevel": 100,     "batteryLowNotification": true,     "categories": [       "security"     ],     "configured": true,     "dead": false,     "deadReason": "",     "defInterval": 0,     "deviceControlType": 0,     "deviceIcon": 120,     "emailNotificationID": 0,     "emailNotificationType": 0,     "endPointId": 0,     "firmwareUpdate": {       "info": "",       "progress": 0,       "status": "UpToDate",       "updateVersion": "3.2"     },     "lastBreached": 1602074852,     "log": "",     "logTemp": "",     "manufacturer": "",     "markAsDead": true,     "maxInterval": 0,     "minInterval": 0,     "model": "",     "nodeId": 21,     "parametersTemplate": "802",     "pendingActions": false,     "productInfo": "1,15,7,2,16,0,3,2",     "pushNotificationID": 0,     "pushNotificationType": 0,     "saveLogs": true,     "serialNumber": "h'0000000000012661",     "smsNotificationID": 0,     "smsNotificationType": 0,     "stepInterval": 0,     "tamper": false,     "updateVersion": "",     "useTemplate": true,     "userDescription": "",     "value": false   },   "actions": {     "abortUpdate": 1,     "reconfigure": 0,     "retryUpdate": 1,     "setInterval": 1,     "startUpdate": 1,     "updateFirmware": 1   },   "created": 1601569356,   "modified": 1601569356,   "sortOrder": 50 }

**Comment by Damianeq90** [comment]
In Attachment
[door.txt](https://github.com/ilcato/homebridge-fibaro-hc3/files/5342254/door.txt)

**Comment by ilcato** [comment]
@Damianeq90 , I just published version 1.0.5 that contains the @Sinoples changes.

**Comment by Damianeq90** [comment]
Thank you! It works :)
